### 负定矩阵

In [5]:
import numpy as np
A = np.array([[-2,-3,-1],
              [-3,-6,-4],
              [-1,-4,-5]])
v = np.array([-2,-3,-7])
print('给定向量任意向量v：',v)
print('求解矩阵A正定判定条件结果是：',v.T.dot(A).dot(v))

给定向量任意向量v： [-2 -3 -7]
求解矩阵A正定判定条件结果是： -539


### 正定矩阵

In [15]:
import numpy as np
A = np.array([[5,1,-4],
              [1,3,-2],
              [-4,-2,7]])
v = np.random.randint(-50,50,size = 3)
print('给定向量任意向量v：',v)
print('求解矩阵A正定判定条件结果是：',v.dot(A).dot(v))

给定向量任意向量v： [-5  8 -3]
求解矩阵A正定判定条件结果是： 276


### 根据特征值进行判定

#### 特征值全部是负数负定矩阵

In [16]:
import numpy as np
A = np.array([[-2,-3,-1],
              [-3,-6,-4],
              [-1,-4,-5]])
w,v = np.linalg.eig(A)
print('矩阵A的特征值特征向量是：')
display(w,v)

矩阵A的特征值特征向量是：


array([-10.54287655,  -0.03922866,  -2.41789479])

array([[ 0.32798528,  0.73697623, -0.59100905],
       [ 0.73697623, -0.59100905, -0.32798528],
       [ 0.59100905,  0.32798528,  0.73697623]])

#### 特征值全部是正数正定矩阵

In [17]:
import numpy as np
A = np.array([[5,1,-4],
              [1,3,-2],
              [-4,-2,7]])
np.linalg.eig(A)

(array([10.74515039,  1.63251546,  2.62233415]),
 array([[-0.58123713, -0.60851363, -0.54025416],
        [-0.27299496, -0.4796241 ,  0.83392714],
        [ 0.76657495, -0.63219608, -0.11265418]]))