### 逆矩阵求方程

In [2]:
# 三元一次方程 
# 3x + 2y + 4z = 19 
# 2x -y + 3z = 9 
# x + y - z = 0

# 方程解就是：1,2,3
import numpy as np
X = np.array([[3,2,4],
              [2,-1,3],
              [1,1,-1]])
y = np.array([19,9,0])
display(X,y)

array([[ 3,  2,  4],
       [ 2, -1,  3],
       [ 1,  1, -1]])

array([19,  9,  0])

In [4]:
# 逆矩阵
np.linalg.inv(X).dot(y)

array([1., 2., 3.])

### 行列式

In [8]:
import numpy as np
A = np.array([[1,3],[3,9]])
display(A) # 1 * 7 - 3 * 3 = -2

print('numpy函数计算行列式：',np.round(np.linalg.det(A)))

array([[1, 3],
       [3, 9]])

numpy函数计算行列式： 0.0


In [12]:
np.linalg.inv(A)

LinAlgError: Singular matrix

In [9]:
B = np.random.randint(0,10,size = (5,5))
B

array([[7, 1, 4, 3, 5],
       [5, 9, 7, 4, 6],
       [2, 8, 5, 9, 4],
       [4, 5, 5, 0, 0],
       [1, 2, 8, 8, 2]])

In [10]:
np.linalg.det(B)

-9803.999999999989

In [11]:
np.linalg.inv(B)

array([[ 0.16319869, -0.1744186 ,  0.10199918,  0.15361077, -0.08873929],
       [-0.06813545,  0.02906977,  0.08241534,  0.0621175 , -0.08170135],
       [-0.0624235 ,  0.11046512, -0.16401469,  0.01499388,  0.15269278],
       [ 0.05915953, -0.15697674,  0.1619747 ,  0.0119339 , -0.00091799],
       [-0.000408  ,  0.24418605, -0.125255  , -0.24663403,  0.01897185]])

### 伴随矩阵求解逆矩阵

In [16]:
import numpy as np
A = np.array([[1,2,3],
              [2,2,1],
              [3,4,3]])
display(A)
display('A矩阵的逆矩阵是：',np.linalg.inv(A))

array([[1, 2, 3],
       [2, 2, 1],
       [3, 4, 3]])

'A矩阵的逆矩阵是：'

array([[ 1. ,  3. , -2. ],
       [-1.5, -3. ,  2.5],
       [ 1. ,  1. , -1. ]])

In [17]:
A_bs = [] # 伴随矩阵
n = 3 # 矩阵A3行3列

# 两层for循环可以遍历每一个元素
for i in range(n):
    for j in range(n):
        row = [0,1,2]
        col = [0,1,2]
        row.remove(i) # 元素a_ij删除行i
        col.remove(j) # 元素a_ij删除列j
        # 代数余子式
        M_ij = A[np.ix_(row,col)] # 剔除行和列剩下的数据
        M_ij = np.linalg.det(M_ij) # 余子式
        A_ij = ((-1)**(i +j)) * M_ij # 代数余子式
        A_bs.append(A_ij)
        
# 求解了伴随矩阵        
A_bs = np.array(A_bs).reshape(3,3).T # 1、reshape；2、转置

# 求解逆矩阵
print('伴随矩阵和行列式求解的逆矩阵是：\n',A_bs/np.linalg.det(A))

伴随矩阵和行列式求解的逆矩阵是：
 [[ 1.   3.  -2. ]
 [-1.5 -3.   2.5]
 [ 1.   1.  -1. ]]


In [18]:
np.linalg.inv(A)

array([[ 1. ,  3. , -2. ],
       [-1.5, -3. ,  2.5],
       [ 1. ,  1. , -1. ]])